--- Tabelas iniciais
CREATE TABLE TB_CLIENTE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(150) NOT NULL,
    IDADE INTEGER,
    NOME VARCHAR(150) NOT NULL
);

CREATE TABLE TB_PRODUTO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MARCA_DO_PRODUTO VARCHAR(150),
    NOME_DO_PRODUTO VARCHAR(150) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    QUANTIDADE_EM_ESTOQUE INTEGER NOT NULL
);

CREATE TABLE TB_PEDIDO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DATA_DO_PEDIDO TIMESTAMP(6) NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES TB_CLIENTE(ID)
);

CREATE TABLE TB_ITEM_PEDIDO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRECO_PEDIDO DECIMAL(10,2) NOT NULL,
    QUANTIDADE_PEDIDO INTEGER NOT NULL,
    ID_PEDIDO BIGINT NOT NULL,
    ID_PRODUTO BIGINT NOT NULL,
    CONSTRAINT FK_ITEM_PEDIDO_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES TB_PEDIDO(ID),
    CONSTRAINT FK_ITEM_PEDIDO_PRODUTO
        FOREIGN KEY (ID_PRODUTO)
        REFERENCES TB_PRODUTO(ID)
);